"""empty message

Revision ID: a51afb254f9b
Revises: 
Create Date: 2019-04-23 03:19:14.720229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51afb254f9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_argument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arguments_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('agree_or_disagree', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['arguments_id'], ['arguments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'location')
    op.drop_column('user', 'name')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.drop_table('single_argument')
    # ### end Alembic commands ###
